### ISSUE TITLE
Exception in DockContentPresenter

### ISSUE THREAD

**Issue by adam-adorjan** [npolyak/NP.Ava.UniDock#15]
Thanks for the upgrade to Avalonia 11!! We are currently integrating it into our product and noticed an exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at NP.Utilities.ReflectionUtils.SetFieldValue(Object obj, String fieldName, Object val, Boolean includeNonPublic, Type realType)
   at NP.Ava.UniDock.DockContentPresenter.OnPropertyChanged(AvaloniaPropertyChangedEventArgs change)
   at Avalonia.Animation.Animatable.OnPropertyChangedCore(AvaloniaPropertyChangedEventArgs change)

We tracked it down to the following code:
    case nameof(UseLayoutRounding):
    case nameof(BorderThickness):
        this.SetFieldValue("_layoutThickness", null!, true);

The logic isn't finding _layoutThickness because the .NET reflection logic doesn't look in base classes for some reason.  Can you please take a look? Thanks!

**Comment by npolyak** [comment]
Thanks Adam, I'll look into it on Sunday, Feb 11.

**Comment by npolyak** [comment]
Thanks for reporting this issue. I fixed it. Please, update your unidock reference to NP.Ava.UniDock.1.0.6

**Comment by npolyak** [comment]
Please, also test it and close the issue.

**Comment by adam-adorjan** [comment]
Looks good! Thx!
