### ISSUE TITLE
Submodule error when cloning

### ISSUE THREAD

**Issue by Mrxx99** [npolyak/NP.Ava.UniDock#2]
When I try to clone this repository with submodules (` git clone --recurse-submodules https://github.com/npolyak/NP.Ava.UniDock`) I get the following error in git log:

```
fatal: No url found for submodule path 'SubModules/NP.IoCy/SubModules/NP.Utilities' in .gitmodules
fatal: Failed to recurse into submodule path 'SubModules/NP.IoCy'
```

**Comment by npolyak** [comment]
> When I try to clone this repository with submodules (` git clone --recurse-submodules https://github.com/npolyak/NP.Ava.UniDock`) I get the following error in git log:
> 
> ```
> fatal: No url found for submodule path 'SubModules/NP.IoCy/SubModules/NP.Utilities' in .gitmodules
> fatal: Failed to recurse into submodule path 'SubModules/NP.IoCy'
> ```

Try cloning first without --recursive

and then cd into the local repository clone

and then type

git submodule update --init

**Comment by npolyak** [comment]
no need to recursively get all submodules - they can all be on the same level.

**Comment by npolyak** [comment]
closing this issue - should work
