### ISSUE TITLE
How to change the Font/TextBlock Color of the Tab .

### ISSUE THREAD

**Issue by henrrymoraes83** [npolyak/NP.Ava.UniDock#4]
Hi Nick Polyak,

It's not a issue, but a technical question.

Firstly, I would like to thank you for the contribution of knowledge and content that you make to the software development community. Much of my learning on Avalonia came from reading the articles you published on the CodeProject website.

And thanks also for the new release of NP.UniDock for Avalonia 11.

I'm trying to customize the colors of the Np.UniDock Tab to support Dark and Light themes, I put the code below in my Window AXAML file and I was able to change the background color, but I was unable to change the Font/TextBlock Color of the Tab .

How to change the Font/TextBlock Color of the Tab , I mean, change the Foreground?

```
 <Window.Styles>

	  <!-- Tab line color -->
	  <Style Selector="np|TabbedDockGroup[IsFullyActive=True]">
		  <Setter Property="TabSeparatorBackground"
			  Value="#7092BE"/>
		  <!--{StaticResource StatusBarBackground}-->
	  </Style>

	  <!-- Background color of current Tab -->
	  <Style Selector="np|DockTabItem.Dock[IsActive=True]">
		  <!-- ??? -->
		  <Setter Property="Background"
				  Value="{StaticResource DockSelectedBrush}"/>
	  </Style>
  </Window.Styles>
```

How to change the color of the two fonts/TexBlock, from the active tab and the one that is not?

![image](https://github.com/npolyak/NP.Ava.UniDock/assets/135464720/daed3a58-de87-4868-b3dc-0364c062d3d6)

**Comment by henrrymoraes83** [comment]
I made the change directly in the DataTemplate but it changes the color of all TextBoxes, it does not differentiate between the Tab that is active and that is not.

```
<DataTemplate x:Key="StockHeaderDataTemplate">
	<TextBlock Text="{Binding Path=Symbol, StringFormat='Symbol: \{0\}'}" Foreground="LightSlateGray" FontWeight="Bold" >
	</TextBlock>
</DataTemplate>
```

**Comment by npolyak** [comment]
Sorry for the delay answering - I have a full time job and essentially can only work on Sundays and during my vacation time. I'll check it tomorrow for you. Should not be very difficult.

**Comment by npolyak** [comment]
I created a small sample for you - the selected tabs have red foreground. 

![image](https://github.com/npolyak/NP.Ava.UniDock/assets/2833722/b0004f26-1eb3-4bff-82a9-82a8a7cbc639)

**Comment by npolyak** [comment]
The for this sample is under [NP.Demos.ChangeForeground](https://github.com/npolyak/NP.Ava.Demos/tree/main/NP.Demos.UniDockFeatures/NP.Demos.ChangeForeground).

All I had to do is to modify the App.axaml file inserting a referent to np.com/visuals xml namespace at the top:
      
      xmlns:np="https://np.com/visuals"

and adding a special style for selected tab:

     	    <Style Selector="np|DockTabItem.Dock[IsSelected=True]">
		    <Setter Property="Foreground"
				    Value="Red"/>
	    </Style>

at the end of App.axaml Styles section.

**Comment by npolyak** [comment]
please tell me if this works for you

**Comment by quantproai** [comment]
Nick,

It worked correctly. Thank you very much! Th

```
<Style Selector="np|DockTabItem.Dock[IsSelected=True]">
	    <Setter Property="Foreground"
			    Value="Red"/>
</Style>

<Style Selector="np|DockTabItem.Dock[IsSelected=False]">
	    <Setter Property="Foreground"
			    Value="Red"/>
</Style>
```

**Comment by npolyak** [comment]
Pleasure :)

Please star the NP.Avi.UniDock repository if you have not done so yet.

**Comment by quantproai** [comment]
Worked perfectly. Thank you so much!! 

```
<Style Selector="np|DockTabItem.Dock[IsSelected=True]">
	    <Setter Property="Foreground"
			    Value="Red"/>
</Style>

<Style Selector="np|DockTabItem.Dock[IsSelected=False]">
	    <Setter Property="Foreground"
			    Value="Green"/>
</Style>
```

**Comment by henrrymoraes83** [comment]
Worked perfectly. Thank you so much!!
Worked perfectly. Thank you so much!!

```
<Style Selector="np|DockTabItem.Dock[IsSelected=True]">
	    <Setter Property="Foreground"
			    Value="Red"/>
</Style>

<Style Selector="np|DockTabItem.Dock[IsSelected=False]">
	    <Setter Property="Foreground"
			    Value="Green"/>
</Style>
```

**Comment by npolyak** [comment]
You are very welcome!
