### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by StefanKoell** [npolyak/NP.Ava.UniDock#5]
Hi,

I tried to clone/build from source but I'm not sure how. I can see a .csproj file in the /src folder but there's no .sln file. Am I missing something? Would love to tweak some stuff and maybe contribute using PRs in the future.

Regards,
Stefan

**Comment by npolyak** [comment]
Hey Stefan,
first you clone, then initialize the submodules (this is an important step, nothing will compile without submodules) - smth line 
git submodule update --init
then cd to one of the prototypes (e.g. Prototypes/NP.DataContextSample) - start the prototype solution from there (e.g. NP.DataContextSample.sln)
From that solution - you can build not only the prototype, but also NP.Ava.UniDock

**Comment by StefanKoell** [comment]
Thanks, that worked.
